# config
cover: /img/img-bg.jpg
bio: 'A designer, developer and entrepreneur. Spends his time travelling the world with a single backpack and head full of ideas'
location: Chiang Mai, Thailand
website: http://kyrisu.com

# Add social network profile links
social:
  twitter: https://twitter.com/kyrisu
  google+: https://plus.google.com/+KrystianPaszkiewicz
  github: https://github.com/kyrisu

#opengraph
twitter_profile: 
googleplus_profile: 
fb_admins:
fb_app_id:

fancybox:
fitvids:

excerpt_link: Read More

# Miscellaneous
rss: /atom.xml
